---
- hosts: test
  become: True
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Start the container
      docker_container:
        name: nodetest
        image: "cranifax/nodetest:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 8060:80
